app/forms/auth_forms.py
from flask_wtf import FlaskForm, RecaptchaField
from wtforms import StringField, TextField, BooleanField, PasswordField
from wtforms.validators import DataRequired, Email, EqualTo

from ..utils.mixins import please_enter

class LoginForm(FlaskForm):
    '''
    LoginForm:
    This Class defines the structure an validation of the Login form
    '''
    username = TextField('Username', validators=[please_enter('your', 'username'),])
    password = PasswordField('Password', validators=[please_enter('your', 'password')])
    remember_me = BooleanField('Remember me.')

class RegisterForm(FlaskForm):
    '''
    RegisterForm:
    This Class defines the structure an validation of the SingUp form
    '''
    name = StringField('Name', validators=[please_enter('your', 'name')])
    # email = TextField(
    #     'Email',
    #     validators=[
    #         please_enter('your', 'email address'),
    #         Email('Please enter a valid email address')
    #     ]
    # )
    username = TextField('Username', validators=[please_enter('username'),])
    password = PasswordField(
        'Password',
        validators=[
            please_enter('password'),
            EqualTo('confirm_password', message='Passwords must match')
        ]
    )
    confirm_password = PasswordField()
    # recaptcha = RecaptchaField()

app/forms/home_forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired

class HomeForm(FlaskForm):
    '''
    HomeForm:
    This Class defines the structure an validation of the home form
    '''
    name = StringField('Name', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])

app/__init__.py
'''
Modulo que inicia y configura la Aplicación de Flask
'''
from flask import Flask, render_template
from werkzeug.exceptions import HTTPException
from flask_wtf.csrf import CSRFProtect
from flask_login import LoginManager

# Services
from .utils.user_auth import User
from .utils.api_client import APIClient


def create_app(testing=False):
    # Instantiate app.
    app = Flask(__name__)

    # Set app configuration
    config(app, testing)

    # Define login manager
    login_manager(app)

    # Define API CLient
    api_client(app)

    # Register app routes.
    register_routes(app)

    # Handle app errors
    handle_errors(app)

    return app


def config(app, testing):

    # Define app config
    app.config.from_object('config')
    if testing:
        app.config['TESTING'] = True
        app.config['PRESERVE_CONTEXT_ON_EXCEPTION'] = False

    # Forms csrf security
    csrf = CSRFProtect()
    csrf.init_app(app)


def login_manager(app):
    # Set login manager
    login_manager = LoginManager()
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(user_id):
        return User().get(user_id)


def api_client(app):
    api = APIClient.get_instance(app.config['API_PATH'])
    app.config['API_CLIENT'] = api


def register_routes(app):
    # Import views as blueprints
    from .views import Home, Auth

    # Register blueprints.
    app.register_blueprint(Home)
    app.register_blueprint(Auth)


def handle_errors(app):
    # Error handlers.
    @app.errorhandler(HTTPException)
    def handle_http_error(exc):
        return render_template('error.html', error=exc), exc.code

app/views/Home.py
from flask import Blueprint, render_template, flash
from app.forms.home_forms import HomeForm
from app.utils.api_client import APIClient

Home = Blueprint('Home', __name__)

api_client = APIClient.get_instance()

@Home.route('/', methods=('GET', 'POST'))
def index():
    form = HomeForm()
    if form.validate_on_submit():
        flash(
            f'Your info was sended successfully, {form.name.data}! ',
            'success'
        )
    return render_template('index.html', form=form)

@Home.route('/api-call')
def api_call():
    res = api_client.get('')
    return render_template('index.html', response=res)

@Home.route('/api-fail')
def api_call_fail():
    res = api_client.get('sdfsdf')
    return render_template('index.html', response=res)

app/views/__init__.py
from .home import Home 
from .auth import Auth

app/views/auth.py
from flask import Blueprint, render_template, redirect, flash, url_for
from app.forms.auth_forms import LoginForm, RegisterForm
from flask_login import current_user, login_user, logout_user, login_required

from app.utils.user_auth import User
from app.utils.api_client import APIClient

Auth = Blueprint('Auth', __name__)

api_client = APIClient.get_instance()

@Auth.route('/login', methods=('GET', 'POST'))
def login():
    if current_user.is_authenticated:
        return redirect(url_for('Home.index'))

    form = LoginForm()

    if form.validate_on_submit():
        user = User().get(form.username.data)

        if user and user.check_password(form.password.data):
            login_current_user(user)
            flash(f'Welcome {form.username.data}! ', 'info')
            return redirect(url_for('Home.index'))

        flash('Invalid credentials! ', 'danger')    

    return render_template('auth/login.html', form=form)

@Auth.route('/register', methods=('GET', 'POST'))
def register():
    if current_user.is_authenticated:
        return redirect(url_for('Home.index'))
    form = RegisterForm()
    if form.validate_on_submit():
        # Create and save user
        user = User(
            id=form.username.data,
            name=form.name.data,
            password=form.password.data,
            is_admin=True
        )
        # Send msg
        if user.save():
            login_current_user(user)
            flash(f'Your are now singed up! {form.name.data} ({form.username.data})', 'success')
            return redirect(url_for('Home.index'))

        flash('Your are already singed up! Please login!', 'danger')
    return render_template('auth/register.html', form=form)

@Auth.route('/logout')
@login_required
def logout():
    logout_user()
    api_client.set_headers(None)
    return redirect(url_for('Home.index'))


def login_current_user(user):
    login_user(user)
    api_client.set_headers({})

app/templates/components/footer.html
<!-- Footer-->
<footer>
    <div class="container-fluid bg-light py-5 d-flex justify-content-center">
      <div class="row py-4">
        <div class="col-lg-6 col-md-4 mb-4 mb-lg-0">
          <h6 id='about' class="text-uppercase font-weight-bold mb-4">About</h6>
          <p class="font-italic text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
            eiusmod tempor incididunt.</p>
        </div>
        <div class="col-lg-2 col-md-3 mb-4 mb-lg-0">
          <h6 class="text-uppercase font-weight-bold mb-4">Quick Links</h6>
          <ul class="list-unstyled mb-0">
            <li class="mb-2"><a href="" class="text-muted">Login</a></li>
            <li class="mb-2"><a href="" class="text-muted">Register</a></li>
          </ul>
        </div>
        <div class="col-lg-2 col-md-3 mb-4 mb-lg-0">
          <h6 class="text-uppercase font-weight-bold mb-4">Social Links</h6>
          <ul class="list-unstyled mb-0">
            <li class="list-item"><a href="https://facebook.com" target="_blank" title="facebook"><span
                  class="fa fa-facebook">Facebook</span></a>
            </li>
            <li class="list-item"><a href="https://twitter.com" target="_blank" title="twitter"><span
                  class="fa fa-twitter"></span>Twitter</a>
            </li>
            <li class="list-item"><a href="https://instagram.com" target="_blank" title="instagram"><span
                  class="fa fa-instagram"></span>Instagram</a></li>
          </ul>
        </div>
      </div>
      <!-- Copyrights -->
      <div class="text-center">
        <p class="text-muted mb-0 py-2">&copy;2020 {{ config.APP_NAME }} | All rights reserved.</p>
      </div>
    </div>
  </footer>
  <!-- scripts -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
  <script src="{{ url_for('static', filename='main.js') }}" type="text/javascript"></script>
  {% block scripts %}{% endblock %}
</body>

</html>

app/templates/components/header.html
<!-- Header -->
<header>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-sm navbar-light bg-light">
    <div class="container">
      <!-- Navbar Brand -->
      <a class="navbar-brand" href="{{ url_for('Home.index') }}">{{ config.APP_NAME }}</a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNav">
        <!-- Main Navigation -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="#about">About</a>
          </li>
        </ul>

        <!-- TODO define current_user and login or logout -->
        <!-- Login/Logout -->

        <ul class="navbar-nav ml-auto">

          {% if current_user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="userActions" data-toggle="dropdown" aria-haspopup="true"
              aria-expanded="false">{{current_user.name | capitalize}}</a>
            <div class="dropdown-menu" aria-labelledby="userActions">
              <a class="dropdown-item" href="{{url_for('Auth.logout')}}">Logout</a>
            </div>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('Auth.login')}}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{url_for('Auth.register')}}">Register</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
</header>

app/templates/components/messages.html
<!-- Flash Messages -->
{% with messages = get_flashed_messages(with_categories=true) %}

    {% if messages %}

        {% for category, message in messages %}
            <div class="alert alert-{{ category }} alert-dismisible">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span>
                </button>
                {{ message }}
            </div>
        {% endfor %}
        
    {% endif %}

{% endwith %}

app/templates/core/_macros.html
<!-- Put your reusable template code into macros here -->

{% macro input(name, value='', type='text', size=20) -%}
    <input type="{{ type }}" name="{{ name }}" value="{{value|e }}" size="{{ size }}">
{%- endmacro %}

app/templates/core/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">

  <title>{{ config.APP_NAME }}</title>

  <!-- TODO define styles -->
  <!-- meta -->
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="viewport" content="width=device-width,initial-scale=1">

  {% block meta %}{% endblock %}


  <!-- TODO define links such as styles -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link href="{{ url_for('static', filename='main.css') }}" rel="stylesheet" media="screen">

  {% block links %}{% endblock %}

</head>

<body>

  {% include 'components/header.html' %}

  <div class="container my-5">

    <!--  Flash messages -->
    {% include 'components/messages.html' %}

    <!-- Main Content -->

    {% block content %}{% endblock %}

  </div>

  {% include 'components/footer.html' %}

app/templates/error.html
{% extends 'core/base.html' %}

{% block content %}
<div class="jumbotron my-4">
  <div class="text-center">
    <h1>{{ '%s - %s' % (error.code, error.name) }}</h1>
    <p>{{ error.description }}.</p>
  </div>
</div>
{% endblock %}

app/templates/index.html
{% extends 'core/base.html' %}

{% block content %}


<h1>Welcome!</h1>
<hr>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,
  molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum
  numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium
  optio, eaque rerum! Provident similique accusantium nemo autem. Veritatis
  obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam
  nihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit,
  tenetur error, harum nesciunt ipsum debitis quas aliquid. Reprehenderit,
  quia. Quo neque error repudiandae fuga? Ipsa laudantium molestias eos
  sapiente officiis modi at sunt excepturi expedita sint? Sed quibusdam
  recusandae alias error harum maxime adipisci amet laborum. Perspiciatis
  minima nesciunt dolorem!</p>
<br>

<b>This is WTForm example!</b>
<br><br>

{% if form %}

<form method="POST" action="/">
  {{ form.csrf_token }}
  {{ form.name.label }} {{ form.name(size=20) }}
  <br>
  {{ form.last_name.label }} {{ form.last_name(size=20) }}
  <br><br>
  <input type="submit" value="Send">
</form>

{% endif %}


<section class="container text-center">
  <form method="GET" action="{{url_for('Home.api_call')}}">
    <input type="submit" value="Request API">
  </form>
  <form method="GET" action="{{url_for('Home.api_call_fail')}}">
    <input type="submit" value="Request API Fail">
  </form>
</section>




{% if response %}
<p id="api-response">
  {{ response }}
</p>
{% endif %}

{% endblock %}